export const GET_SUBJECT_LIST = 'GET_SUBJECT_LIST'
// 二级分类
export const GET_EDUSUBJECT_LIST = 'GET_EDUSUBJECT_LIST'
// 更新数据
export const GET_UPDATESUBJECT_LIST = 'GET_UPDATESUBJECT_LIST'
// 删除数据
export const GET_DELETESUBJECT_LIST = 'GET_DELETESUBJECT_LIST'
